### ISSUE TITLE
I got an error when i build my project.

### ISSUE THREAD

**Issue by Churchson** [cuikangjie/js-export-excel#12]
I use react 16.4.1 ,when i was developing. It was right.When I build my project, i got the error.

$ node scripts/build.js
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/js-export-excel/src/js-export-excel.js:12

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cuikangjie** [comment]
yarn upgrade js-export-excel

version: 1.1.1 fix the bug
