### ISSUE TITLE
当sheetData采用数组的方式，导出表格的内容区域为空。

### ISSUE THREAD

**Issue by linzelong95** [cuikangjie/js-export-excel#17]
sheetData=[['一行一列','一行二列'],['二行一列','二行二列']];   //**不可以**
sheetData=[{one:'一行一列',two:'一行二列'},{one:'二行一列',two:'二行二列'}];  //可以

**Comment by cuikangjie** [comment]
sheetData 设为数组时  不要设置 sheetFilter
