### ISSUE TITLE
Unexpected token: name (sj) 

### ISSUE THREAD

**Issue by StrangeTown** [cuikangjie/js-export-excel#2]
yarn build 的时候出现了如下错误：

`Unexpected token: name (sj) [./~/js-export-excel/src/json-export-excel.js:12,0][static/js/index.e208170a.js:101337,9]`

**Comment by cuikangjie** [comment]
开发是不会出错？只有build的时候？

**Comment by cuikangjie** [comment]
![image](https://user-images.githubusercontent.com/20765753/30105587-a6767a66-932b-11e7-9f69-fb02d0e0f09f.png)

@StrangeTown 你可以把具体的配置文件贴出来

**Comment by StrangeTown** [comment]
我项目是用 create-react-app 建的，配置文件就是它自己生成的 webpack.config.prod.js

看到其他类似的 issue 说是 Uglify 不识别 es6 语法。然后我在 webpack.config.prod.js 里增加了 babel 对 node_modules 下的 js-export-excel 的处理。又报出了别的错误，好像是和什么 “component” 相关，记不清了。

最后我找了一段生成 csv 文件的代码拿过来用了。。。

**Comment by cuikangjie** [comment]
代码是用es6写的  需要使用bable-loader 进行编译

**Comment by hxdyj** [comment]
打包使用
new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
报错
ERROR in build.js from UglifyJs
Unexpected token: name (sj) [./~/_js-export-excel@1.0.3@js-export-excel/src/json-export-excel.js:12,0][build.js:38074,9]
