### ISSUE TITLE
多级标题如何导出

### ISSUE THREAD

**Issue by Augustzyh** [cuikangjie/js-export-excel#27]
对于有多层层级关系的表头的表格怎么导出呢

**Comment by huapisong** [comment]
# 参考 希望可以有帮助
##  修改 js-export-excel.js 
// # 添加二级标题 
workbook: {
            SheetNames: [],
            Sheets: {},
            merges: [],
            sheetHeaderSecond: [],
        }, 
// 在标题下一行添加
                let sheetHeaderSecond= _options.sheetHeaderSecond || data.sheetHeaderSecond;
                if (sheetHeaderSecond && sheetHeaderSecond.length > 0) {
                    sheetData.unshift(sheetHeaderSecond);
                }
// 添加合并规则
                if (!ws['!merges']) ws['!merges'] = [];
                let merge = (_options.merges || data.merges) || [];
                // ws['!merges'].push(merge);
                ws['!merges'] = merge;
##  具体使用
import ExportJsonExcel from"@/common/js-export-excel";
//  sheetHeaderSecond: ['二级标题', '二级标题', '二级标题', '二级标题', '二级标题','二级标题' ],
itemContent= {
                                  sheetData: sheetData,
                                  sheetName: sheetName,
                                  merges: [{ s: {r:1, c:1}, e: {r:1, c:6} }], // 合并
                                  sheetHeaderSecond:sheetHeaderSecond, // 二级标题
                                  sheetFilter:filterData,
                                  sheetHeader:headerData // 一级标题
                                };

                                option.datas.push(itemContent);
                               let toExcel = new ExportJsonExcel(option);
                               toExcel.saveExcel();

**Comment by cuikangjie** [comment]
在sheetData里 第一条数据设置二级标题就可以了

**Comment by anke1460** [comment]
目前版本，第一条数据设置二级标题, 表头不会合并吧？

**Comment by huapisong** [comment]
![图片](https://github.com/kinddde/js-export-excel/assets/45380173/36c23a4e-5972-4df2-a5cb-4b27d336d67f)
headerMerge: ['合并标题', '', '', '', '', '', '账合并标题', '', '', '', '', '', '合并标题‘, '', ''],
