### ISSUE TITLE
es6使用该项目打包会出现问题。

### ISSUE THREAD

**Issue by HeSwift** [cuikangjie/js-export-excel#4]
打包会出现Unexpected token: name (sj) [8.5c86bdf0.async.js:49105,9]

**Comment by cuikangjie** [comment]
你用babel-loader了吗

**Comment by cuikangjie** [comment]
![image](https://user-images.githubusercontent.com/20765753/32880344-4abf46f4-cae8-11e7-8247-1f28bd07db2c.png)
![image](https://user-images.githubusercontent.com/20765753/32880364-5735e8b6-cae8-11e7-99a9-6bb41647d324.png)

**Comment by hxdyj** [comment]
我的也是，一样的错误

**Comment by hxdyj** [comment]
使用Uglify插件打包才会出错

**Comment by HUANGSHENGBO** [comment]
同样的问题,请问是怎么解决的?
