### ISSUE TITLE
Does it export hyperlink as excel value?

### ISSUE THREAD

**Issue by ayush17** [cuikangjie/js-export-excel#40]
Requirement- It should export hyperlink as well for excel values

**Comment by cuikangjie** [comment]
verion 1.1.3 start to support exporting Blob objects, you can expand on this basis.

```js
let option={
saveAsBlob:true,
datas:[......]
};

var toExcel = new ExportJsonExcel(option); 

let blob = toExcel.saveExcel();

```

**Comment by ayush17** [comment]
@cuikangjie _**Does it will export hyperlink?

like in below code. THere is link coloumn. How do I save link column as link in excel?**_

export const exportExcel=(data,enteredSearchNotCreated,date,type)=>{
  let option={};
    let dataTable=data.reduce((dataTable,data)=>{
      let obj = {
        'Dossier Coordinator': data.dossierCoordinatorContact?data.dossierCoordinatorContact:'Not Available',
        'Submission ID': data.submissionId? data.submissionId:'',
        'Submission Name': data.submissionName?data.submissionName:'',
        'Market':data.market?data.market:'Not Available',
        'Submission Category':data.submissionCategory?data.submissionCategory:'Not Available',
        'Product':data.productFamily?data.productFamily:'Not Available',
        'Projected Hand Off To Pco':data.handOffToPcoProjected?isDateStringValidDate(data.handOffToPcoProjected)?getUTCDate(data.handOffToPcoProjected):data.handOffToPcoProjected:'Not Applicable',
        'Projected Ra Submission':data.raSubmissionProjected?isDateStringValidDate(data.raSubmissionProjected)?getUTCDate(data.raSubmissionProjected):data.raSubmissionProjected:'Not Available',
        'Base Case Approval':data.baseCaseApproval?isDateStringValidDate(data.baseCaseApproval)?getUTCDate(data.baseCaseApproval):data.baseCaseApproval:'Not Applicable', 
        'Submission Due Date':data.submissionDueDateDetails?data.submissionDueDateDetails.submissionDueDate?isDateStringValidDate(data.submissionDueDateDetails.submissionDueDate)?getUTCDate(data.submissionDueDateDetails.submissionDueDate):data.submissionDueDateDetails.submissionDueDate:'Not Available':'Not Available',
        'Critical Path':data.criticalPath?data.criticalPath.criticalPathName?data.criticalPath.criticalPathName:enteredSearchNotCreated?'Not Applicable':'Not Available':enteredSearchNotCreated?'Not Applicable':'Not Available',
        'Planning Status':data.planningStatus?getPlanStatus(data.planningStatus, data.atRisk,data.onTrack):'Not Available',
        'Link':window.location.href?`${window.location.href}-detail?subId=${data.submissionId}`:'Not Available'
      }
       dataTable.push(obj);
     return dataTable;
    },[])

  option.datas = [
    {
      sheetData: dataTable,
      sheetName: 'sheet',
      sheetFilter: ['Dossier Coordinator', 'Submission ID', 'Submission Name', 'Market', 'Submission Category', 'Product', 'Projected Hand Off To Pco', 'Projected Ra Submission', 'Base Case Approval', 'Submission Due Date', 'Critical Path', 'Planning Status','Link'],
      sheetHeader: ['Dossier Coordinator', 'Submission ID', 'Submission Name', 'Market', 'Submission Category', 'Product', 'Projected Hand Off To Pco', 'Projected Ra Submission', 'Base Case Approval', 'Submission Due Date', 'Critical Path', 'Planning Status','Link'],
    }
  ];
  const toExcel = new ExportJsonExcel(option);
  toExcel.saveExcel();
}`

**Comment by ayush17** [comment]
@cuikangjie Please can you clarify me here. Sorry it is urgent actually.

**Comment by kinddde** [comment]
Please upgrade to version 1.1.4, eg: hyperlink: https://www.baidu.com

https://github.com/cuikangjie/js-export-excel#sheet-option

**Comment by ayush17** [comment]
@cuikangjie I don't want data source from an external link. That is not what I am asking. The real problem that I am facing is I want **link** as cell value.But it is coming as text

**Comment by ayush17** [comment]
![Screenshot from 2020-07-30 15-51-06](https://user-images.githubusercontent.com/16875079/88912367-cae4ee80-d27c-11ea-8afa-8b104b9b8c43.png)

**Comment by ayush17** [comment]
@cuikangjie It is not coming as clickable text. It is coming as just text

**Comment by kinddde** [comment]
![image](https://user-images.githubusercontent.com/20765753/88995321-eacbef00-d31c-11ea-9471-21ee41a7fc24.png)

you can see the example demo, it is  as clickable text.

Now does not support text and link different, future v2.0 will supported.

you still have other questions. Please write a codesandbox.

**Comment by ayush17** [comment]
@cuikangjie 
https://jsfiddle.net/sheetjs/24nxpek8/

**Comment by kinddde** [comment]
I know this api, but currently js-export-excel does not support this data format, you can directly use the xlsx package to export the data
