### ISSUE TITLE
能不能支持返回Blob格式数据，不直接下载

### ISSUE THREAD

**Issue by hkaikai** [cuikangjie/js-export-excel#41]
能不能支持返回Blob格式数据，不直接下载，有时候需要上传或者压缩之类的

**Comment by cuikangjie** [comment]
1.1.3 已经发布，添加saveAsBlob配置，导出blob格式数据

不建议使用该插件进行上传，直接传给后端json数据更直接

**Comment by hkaikai** [comment]
> 1.1.3 已经发布，添加saveAsBlob配置，导出blob格式数据
> 
> 不建议使用该插件进行上传，直接传给后端json数据更直接

非常感谢
