### ISSUE TITLE
npm仓库里的版本1.0.3里面class语法报错

### ISSUE THREAD

**Issue by caoliangsong** [cuikangjie/js-export-excel#9]
npm仓库里的版本1.0.3里面class语法报错，babel不会自动转码node_modules里面的js文件

**Comment by cuikangjie** [comment]
报什么错

**Comment by heyunjiang** [comment]
是否可以考虑，从node_modules把js-export-excel源码拷到项目中，通过在项目中支持es6的babel编译，解决babel不编译node_modules中文件问题

**Comment by cuikangjie** [comment]
可以， 但测试过babel编译都是ok的 @heyunjiang

**Comment by cuikangjie** [comment]
建议修改webpack配置， 使用babel编译node_modules

**Comment by zhangzhengyi12** [comment]
同样问题，主要好像是两个方面 
第一 export default const exportExcel
第二 最后的CMD模块导出  module.exports = exportExcel;

我的解决办法是： 修改第一项为  const exportExcel = xxx  ; export default exportExcel 然后删除第二项模块导出语法， 其实我也不是很懂webpack对于CMD模块的支持，看起来似乎无法同时使用两种模块语法？ 

另外东西很棒
